### ISSUE TITLE
你好，按文档中的步骤server和mall 都报错了

### ISSUE THREAD

**Issue by whynogo** [yzbgyq/Vue-shopping#1]
mail：this dependence was not found：
*vant/lib/want-css/index.css in .src/main.js 
按提示安装vant后也是如此

server  app.js 40行报错，语法错

请问是文件没有上传完全吗？

**Comment by yzbgyq** [comment]
原来是vant版本更新了问题，改下就行，在main .js里面改成'vant/lib/index.css'或者重新下拉仓库

**Comment by yzbgyq** [comment]
要安装好mongodb数据库并且打开连接才能server的脚本

**Comment by whynogo** [comment]
谢了，可以看到部分UI了

**Comment by yzbgyq** [comment]
我重新更新过代码了，做了很大的变化
