### ISSUE TITLE
为什么直接访问3000的url无法获得验证码，通过8090就可以？

### ISSUE THREAD

**Issue by MillionQW** [yzbgyq/Vue-shopping#3]
首先感谢作者的项目，为我搭建自己的 vue + egg + mongoDB 的项目提供了很好的参考~

在我研究代码的时候，发现如果直接访问 ```127.0.0.1:3000/api/verify``` 的时候是无法获取验证码的，只有访问```127.0.0.1:8090/api/verify``` 才有验证码返回。

我通过把 router/api.js 里的路由路径做了修改和对 生成验证码的代码做了修改实现了直接访问服务器地址返回验证码：
```
// router/api.js/
module.exports = app => {
  const { router, controller } = app;
  // 增加 '/api/'
  router.get('/api/verify', app.controller.base.verify); // 验证码
}
```
```
// service/tools.js
class ToolsService extends Service {
  // 产生验证码
  async captcha() {
   // 使用 svgCaptcha.create()
    const captcha = svgCaptcha.create({
      size: 4,
      fontSize: 50,
      width: 100,
      height: 40,
      background: '#cc9966'
    });
    this.ctx.session.code = captcha.text;
    return captcha;
  }
}
```

有两个疑问想问作者：
为什么无法直接通过服务器地址获取验证码
svg-captcha 的使用说明上说要调用```svgCaptcha.create()```才能返回验证码为什么作者直接调用 ```svgCaptcha()```就能返回

**Comment by yzbgyq** [comment]
1，是这样的，前端项目和后端项目一共起了两个端口，一个是前端8090，一个是后端3000，这两个端口不一样产生了跨域，就是说前端通过ajaxx直接请求后端api接口是拿不到数据的，所以在vue里面config文件下面的index.js里面**proxyTable**设置了本地跨域代理，就是在所有前端所有接口请求前面加上 /api 前缀，所以能拿到数据，而后端不需要加前缀，直接能拿到数据，也就是说前端要拿到验证码必须 **http://127.0.0.1:8090/api/verify**  这样才能拿到验证码，而后端直接 访问**http://127.0.0.1:3000/verify**就能看到验证码，也就是说前端请求接口地址，加了个前缀 /api，而后端访问就不需要加这个/api,
2，第二个问题我不是很理解，我确实调用了svgCaptcha.create()才生成验证码的，不调用生成不了

**Comment by MillionQW** [comment]
1. 明白了~ 之前都是访问的```http://127.0.0.1:3000/api/verify```怪不得拿不到数据。
2. 天，又看了下你的源码有调 ```create()```...可能拉下来后```crerate()```被我误删了。
3. 有个小建议，在 ```controller/api/user.js```里，```login()```和```register()```都有相同的表单信息校验代码：
```
if (!nickname || !password) {
            return ctx.body = {
                code: -1,
                msg: '请输入完整信息'
            }
        }
        if (this.ctx.session.code.toUpperCase() !== verify.toUpperCase()) {
            return ctx.body = {
                code: -2,
                msg: '验证码错误'
            }
        }
```
建议可以把这一段代码从 controller 提取出来放到 service 层做，可以提高代码的复用性~ 

最后再次感谢你的开源代码。

**Comment by yzbgyq** [comment]
谢谢你的建议哈，有空加个微信一起交流，微信xiaobai11779
