### ISSUE TITLE
怎么样本地测试接口

### ISSUE THREAD

**Issue by LadyChatterleyLover** [yzbgyq/Vue-shopping#8]
我想在postman测试接口，首页接口就报未登录，怎么办啊

**Comment by yzbgyq** [comment]
![456d9da2e163e198e8eaef009521f38](https://user-images.githubusercontent.com/32931212/56865456-9989cd00-6a00-11e9-97e1-f05b7da78d7d.png)
有几个接口是要登录才能访问，把权限去掉就行了

**Comment by LadyChatterleyLover** [comment]
好的 兄弟 加个qq或者微信 有些具体的东西想问下你

**Comment by yzbgyq** [comment]
微信xiaobai11779
